version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  compile-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run: yarn install
      - run: yarn compile
      - run: yarn test
workflows:
  compile-and-test:
    jobs:
      - compile-and-test