version: 2.1

orbs:
  node: circleci/node@5.02
  yarn: itinerisltd/yarn@2.1.1
jobs:
  compile-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - run: yarn install
      - run: yarn compile
      - run: yarn test
workflows:
  compile-and-test:
    jobs:
      - compile-and-test